# Server Configuration
server:
  port: 9090

# Application Configuration
spring:
  application:
    name: API-GATEWAY

  redis:
    host: localhost
    port: 6379

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/healthconnect-realm
          jwk-set-uri: http://localhost:8080/realms/healthconnect-realm/protocol/openid-connect/certs

# Rate Limiter Configuration
rate-limiter:
  replenish-rate: 10
  burst-capacity: 20
