# Application Configuration
spring:
  application:
    name: ServiceRegistry

# Server Configuration
server:
  port: 8761

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    renewal-threshold-update-interval-ms: 15000

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
