# Server Configuration
server:
  port: 8083

# Application Configuration
spring:
  application:
    name: USER-SERVICE

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    ddl-auto: create
    generate-ddl: true

swagger:
  base-package: com.healthconnect.userservice
  title: User Service API Documentation
  description: API documentation for the User Management service of Healthcare Connect.
  version: v1